### PR TITLE
support RPR

### PR DESCRIPTION
**Pull request by nuomi2021**

### CODE REVIEW

**Comment by nuomi2021** [comment]
@frankplow , could you help upload the original DVB files (ts and mp4) to our test set? so we can announce we are compatible with DVB
thank you

**Comment by frankplow** [comment]
> @frankplow , could you help upload the original DVB files (ts and mp4) to our test set? so we can announce we are compatible with DVB thank you

I've given all the plain MPEG-TS files a go, they match the extracted bitstreams so no unexpected failures there.  I'll put a patch together to do this on the CI later.

DASH has an upstream issue preventing us from doing end-to-end testing for the time-being.  I've posted a [patch upstream](https://patchwork.ffmpeg.org/project/ffmpeg/patch/20240520201420.92545-1-post@frankplowman.com/) but in the meantime, shall we just test the .mp4s?

**Comment by nuomi2021** [comment]
@frankplow , Yes. please add mp4 firstly. 
Here are the MD5s. I don't know how to upload the file to Videolan,So I did not submit the patch to the CI.
Thank you.

> 7ed219c65e9738493bce9e01c7c7fc7b  vvc_8b_bt709-ClosedGOP-3840x2160-24fps-60s-4Mbps.mp4
> f774bb460a941e75fed8af1490f97621  vvc_uhd1_hdr-ClosedGOP-3840x2160_50fps-HLG10-60s-38Mbps.mp4
> 86812b55e8a21b0b08ae73c04c3ef95d  vvc_uhd1_pq_dmi-closedGOP-3840x2160-50fps-PQ10-60s-8Mbps.mp4
> 71b6ac107aea43a62ad9954e90d0f125  vvc_uhd2_hfr-ClosedGOP-7680x4320_100fps-SDR-30s-90Mbps.mp4
> 74825eb00366de8b3d097afb8d384cf9  vvc_hdr_reschange-ClosedGOP-3840x2160_50fps-HLG10-60s.mp4
> 6c0c991dbb3eff49de2058fa5366973c  vvc_uhd1_hdr-ClosedGOP-3840x2160_50fps-HLG10-60s-8Mbps.mp4
> b3420b1524d8d7e09c44f2a38758c1c8  vvc_uhd2_hdr-ClosedGOP-7680x4320_50fps-HLG10-30s-12Mbps.mp4
> 2e46a829264723e21d24ee9fae367768  vvc_uhd1_60fps-ClosedGOP-3840x2160_60fps-SDR-60s.mp4
> 903d430d692600f7bf883b6ac365dba6  vvc_uhd1_hfr-ClosedGOP-3840x2160_100fps-SDR-60s-10Mbps.mp4
> afd0697c149396f1a9bf11922c1e8db5  vvc_uhd2_hdr-ClosedGOP-7680x4320_50fps-HLG10-30s-90Mbps.mp4
> ecf69f118264d98752cb5c975f0c1b57  vvc_uhd1_hdr-ClosedGOP-1920x1080_50fps-HLG10-60s-3Mbps.mp4
> 0d71b202051ca9eef1a1d74714a74cc2  vvc_uhd1_hfr-ClosedGOP-3840x2160_100fps-SDR-60s-58Mbps.mp4
> c3276c6bcde46d2b731833071a1ca192  vvc_uhd2_hfr-ClosedGOP-7680x4320_100fps-SDR-30s-15Mbps.mp4

**Comment by nuomi2021** [comment]
https://github.com/FFmpeg/FFmpeg/commit/1b33c9a50a90f919118314fd495ed86418ec1655

**Pull request closed without merging**
