### PR TITLE
Add Windows builds with assembly optimisations enabled to CI

### PR DESCRIPTION
**Pull request by frankplow**
This PR adds two new jobs to CI for building and testing with assembly optimisations enabled and assembled with NASM and YASM on Windows.

Different operating systems are now combined into a single matrix as this is easier to manage with all the combinations of OS/compiler/assembler. I think this will also be more future-proof as different checks and combinations are added. This required using MSYS/MSVC instead of FFVS-Project-Generator. If we still want to check FFVS-Project-Generator can generate a valid VS solution in CI I can add this as a separate job.

The new jobs have flagged an [error when compiling with YASM](https://github.com/frankplow/FFmpeg/actions/runs/4707830898/jobs/8349932081).

### CODE REVIEW

**Comment by frankplow** [comment]
[test / windows/msvc/none failure](https://github.com/frankplow/FFmpeg/actions/runs/4707830898/jobs/8349932022) and [test / windows/msvc/nasm failure](https://github.com/ffvvc/FFmpeg/actions/runs/4707893563/jobs/8350023724) are related to #26 I believe.

**Comment by nuomi2021** [comment]
> The new jobs have flagged an [error when compiling with YASM]

thank you for the pr,it has avx512 :) https://github.com/ffvvc/FFmpeg/actions/runs/4711935904/jobs/8356796175?pr=65#step:6:72
yasm issue fixed by  fixed by https://github.com/ffvvc/FFmpeg/pull/65

> If we still want to check FFVS-Project-Generator can generate a valid VS solution in CI I can add this as a separate job.

Not needed since you already use cl.exe to compile.

**Comment by nuomi2021** [comment]
how about we change none to c_only or no_asm. none can mean many things, we may forget the mean in the short time.

**Comment by frankplow** [comment]
Histories are behaving a little strangely because #67 was branched from [frankplow:ci-enhancements](https://github.com/frankplow/FFmpeg/tree/ci-enhancements) but merged into [FFmpeg:main](https://github.com/ffvvc/FFmpeg/tree/main) before this PR - any chance this can be merged?

**Comment by frankplow** [comment]
Rebased onto main

**Pull request merged**
