### PR TITLE
Add Intra Buffer Copy Support

### PR DESCRIPTION
**Pull request by QSXW**

### CODE REVIEW

**Comment by nuomi2021** [comment]
@QSXW , thank you for the patch. 
Seems all IBC clips have failed. Could you help check? 
thank you
https://github.com/ffvvc/FFmpeg/actions/runs/7233384009/job/19714328903?pr=169#step:11:235

**Comment by QSXW** [comment]
> @QSXW , thank you for the patch. Seems all IBC clips have failed. Could you help check? thank you https://github.com/ffvvc/FFmpeg/actions/runs/7233384009/job/19714328903?pr=169#step:11:235

Sure. It's to be finished. However, I get some weird problem here. I need to fill virtual ibc buffer by the reconstructed pixels. See [fill_ibc_buffer](https://github.com/ffvvc/FFmpeg/pull/169/files#diff-f376ce082576f458c39221056f47f7a3d8b2f647ad7631fcc146d4d62a1be09cR552)

And copy the ibc buffer in the inter prediction stage. See [intra_block_copy](https://github.com/ffvvc/FFmpeg/pull/169/files#diff-73c32d1decdf64ebefe8ad2128c8f58375085339818f61dca718c2d5f52cb45fR944)

I suppose  the decode pipeline should works like: `recon -> fill_ibc_buffer -> inter -> intra_block_copy`, but looks like it is `inter -> intra_block_copy -> recon -> fill_ibc_buffer`. Do you have any idea about it?

**Comment by nuomi2021** [comment]
IBC may need current CTU's left and up CTUs decoded.  It need some tricks to make sure it.
Please set the thread number to 1 in vvcdec.c. check whether it works as you expected or not.
if yes, maybe you need to listen to the current frame's progress. 
see: https://github.com/ffvvc/FFmpeg/blob/main/libavcodec/vvc/vvc_thread.c#L240C13-L240C34

**Comment by nuomi2021** [comment]
replaced by https://patchwork.ffmpeg.org/project/ffmpeg/patch/TYSPR06MB6433D9436D9F75AEB1A2B5D2AA562@TYSPR06MB6433.apcprd06.prod.outlook.com/

thank you @QSXW

**Pull request closed without merging**
