### PR TITLE
test IBC

### PR DESCRIPTION
**Pull request by nuomi2021**

### CODE REVIEW

**Comment by Jamaika1** [comment]
```
In function 'prepare_intra_edge_params_8',
    inlined from 'intra_pred_8' at extra/vvc_intra_template.c:627:5:
extra/vvc_intra_template.c:535:21: warning: writing 16 bytes into a region of size 0 [-Wstringop-overflow=]
  535 |             left[i] = top[i] = left[0];
      |             ~~~~~~~~^~~~~~~~~~~~~~~~~~
extra/vvc_intra_template.c: In function 'intra_pred_8':
extra/vvc_intra_template.c:625:21: note: at offset -105 into destination object 'edge' of size 3136
  625 |     IntraEdgeParams edge;
      |                     ^~~~
```

**Comment by nuomi2021** [comment]
Hi @Jamaika1 
Thank you for reporting this.
could you try the ffmpeg master, or provide the reproduce steps?

thank you

**Comment by Jamaika1** [comment]
Hi nuomi2021
https://github.com/FFmpeg/FFmpeg/commit/7d82daf31da1322226c8be64e6530a2cdf45bde2
plus
https://github.com/ffvvc/FFmpeg/tree/287705d5a1069aae9b664d92543d56207b0eb93e

https://github.com/brechtsanders/winlibs_mingw/releases/download/14.0.0-snapshot20240107posix-11.0.1-msvcrt-r1/winlibs-x86_64-posix-seh-gcc-14.0.0-snapshot20240107-mingw-w64msvcrt-11.0.1-r1.zip
```
echo off
set PATH=C:/gcc1400/bin;%PATH%
rem echo %PATH%
rem cd "C:/gcc1400/bin"

cd libavcodec/vvc
for %%f in ("vvc*.c") do gcc.exe -std=gnu11 -static -march=x86-64-v2 -ftree-vectorize -g0 -O3 -fPIC -mavx -mxsave -mpclmul -maes -DHAVE_AV_CONFIG_H=1 -DBUILDING_avutil=1 -DWINVER=0x0602 -D_WIN32_WINNT=0x0602 -DWIN32_LEAN_AND_MEAN=/"/" -U__STRICT_ANSI__ -D__USE_MINGW_ANSI_STDIO=1 -DCAIRO_WIN32_STATIC_BUILD=1 -DG_LIB_STATIC=1 -DRSVG_STATIC=1 -DKVZ_STATIC_LIB=1 -DUVG_STATIC_LIB=1 -DOPJ_STATIC=1 -DUAVS3D_STATIC=1 -DUAVS3E_STATIC=1 -DLIBTWOLAME_STATIC=1 -c %%f -o %%~nf.o
cd ../..
```
Example codecs VTM/VVENC/ECM:
https://vcgit.hhi.fraunhofer.de/ecm/ECM/-/commit/d044a9de69a15da2a1f1e7fa4e4bc3490685ebdc
https://vcgit.hhi.fraunhofer.de/jvet/VVCSoftware_VTM/-/commit/b4dd0e7d54dc6546281e95a90f7fa70da7a5057e
https://github.com/fraunhoferhhi/vvenc/commit/7dae9ea6904d9338e7e603df49b9402d231580ec
https://www.sendspace.com/file/f2zj4b

**Comment by nuomi2021** [comment]
Pretty wired. 
We may break you again even if we fix this. 
Is it possible for you to help set up the ci for mingw. so we never break you again?

thank you

**Comment by nuomi2021** [comment]
upstreammed.

**Pull request closed without merging**
