### PR TITLE
transform: change coeffs type from int to int32_t

### PR DESCRIPTION
**Pull request by nuomi2021**

### CODE REVIEW

**Comment by nuomi2021** [comment]
@frankplow . please help review. thank you

**Comment by frankplow** [comment]
All LGTM, although I think it will be easier to implement this change as a commit on the #130 branch.

**Comment by nuomi2021** [comment]
sure, let me close this. 
could help create a commit to #130? thank you

**Comment by frankplow** [comment]
👍 I will get this done once I have the size-64 and rectangular transforms working. Note that it will require a significant refactor of the assembly optimisations.

**Pull request closed without merging**
