### PR TITLE
fix negtive tests and merge check asm

### PR DESCRIPTION
**Pull request by nuomi2021**

### CODE REVIEW

**Comment by nuomi2021** [comment]
Tried 2 times.
Seems https://github.com/ffvvc/FFmpeg/issues/68 fixed. @frankplow could you help try and help review?

thank you

**Comment by frankplow** [comment]
@nuomi2021 Just spotted that #68 seems to only affect the main ffvvc-test build now and not checkasm. It being intermittent, I don't think it had occurred for the main test before 68c056f071a543c50395515275a6f26e3223df64 so I didn't think to make the main test build single-threaded also. Sod's law, as soon as we apply that commit it starts affecting both. I've made #71 to do the build in ffvvc-test with a single thread also. Seems to do the trick on my fork, although I've never been able to reproduce the error on there reliably for some reason.

If #71 doesn't seem to do the trick, this PR LGTM. Must admit I don't really understand why - the environment setup is identical between the ffvvc-test and checkasm jobs so combining them shouldn't change much, but if it works it works.

Sorry for not looking into this myself sooner, been busy with work.

**Comment by nuomi2021** [comment]
@frankplow , if we make the main build a single thread. it may be too slow. 
The asm only take 4s better combine it with current test.

**Comment by frankplow** [comment]
@nuomi2021 Yeah, #71 looks to be a few minutes slower than this PR although it does appear to fix the issue. Any chance we can run workflow dispatch a few times on this PR to confirm it fixes the issue? In this PR, FFmpeg is still being built in the same way that caused [this build error](https://github.com/ffvvc/FFmpeg/actions/runs/4787027092/jobs/8511712666#step:7:147) so I think the error might just be relatively rare.

**Comment by nuomi2021** [comment]
Thank you for checking. it's really like a ffmpeg or visual studio issue. Let us merge this since it is faster. 
Thank you for you great help.

**Comment by nuomi2021** [comment]
@frankplow the merge test passed [too](https://github.com/frankplow/FFmpeg/actions/runs/4838370638/jobs/8622782113). 
You are right, maybe the error is rare.

**Pull request merged**
