### PR TITLE
AVX2 accelerated chroma deblocking filter

### PR DESCRIPTION
**Pull request by zackerthescar**
This is a draft PR for the AVX2 accelerated deblocking filter that I wrote. I'm trying to get `ff_vvc_v_loop_filter_8_avx2` to start off. Unfortunately, it currently does not pass `checkasm`. Hoping to get this done sooner than later.  Any tips?

### CODE REVIEW

**Comment by frankplow** [comment]
I think this may be accidental: https://github.com/ffvvc/FFmpeg/pull/110/files#diff-f0b18460e5f0f5478f7175369d062f49f897a1c58a57f39bc48ae502e21d25deL40-R40

**Comment by QSXW** [comment]
Hi. Can you add some performance data like https://github.com/ffvvc/FFmpeg/pull/69？

**Comment by zackerthescar** [comment]
Hey all, thanks for looking at this PR.

> I think this may be accidental: https://github.com/ffvvc/FFmpeg/pull/110/files#diff-f0b18460e5f0f5478f7175369d062f49f897a1c58a57f39bc48ae502e21d25deL40-R40

Turns out this was! Accidentally pushed an experiment!

> Hi. Can you add some performance data like https://github.com/ffvvc/FFmpeg/pull/69%EF%BC%9F

```
[FFmpeg] tests/checkasm/checkasm --test=vvc_deblock --seed=0 --benchmark                                                                                                                                 
benchmarking with native FFmpeg timers
nop: 51.2
checkasm: using random seed 0
AVX2:
 - vvc_deblock.chroma [OK]
checkasm: all 2 tests passed
vvc_v_loop_filter_chroma8_c: 50.2
vvc_v_loop_filter_chroma8_avx2: 32.2
vvc_v_loop_filter_chroma10_c: 41.2
vvc_v_loop_filter_chroma10_avx2: 23.2
```

This is done with the current push. Unfortunately running any test files will cause either a segfault or some other issue.

**Comment by nuomi2021** [comment]
@zackerthescar ,  the main branch switched. 
could you help rebase this? and show the comandline how to reproduce the issue?

thank you.

**Comment by zackerthescar** [comment]
> 

I spent a while today refactoring on the new codebase. This PR will now close and a new one will appear. 

Thanks.

**Pull request closed without merging**
