### PR TITLE
Fix init task

### PR DESCRIPTION
**Pull request by nuomi2021**

### CODE REVIEW

**Comment by nuomi2021** [comment]
@frankplow , this will fix all three files you send me. please help review.

**Comment by frankplow** [comment]
@nuomi2021 LGTM!  Can confirm it fixes the hang with those bitstreams, plus also another ~dozen bitstreams I had which were causing hangs.  Don't have any bitstreams which cause hangs now.

**Comment by frankplow** [comment]
@nuomi2021 Actually it looks like while this patch fixes most hangs, it causes a regression which makes some other bitstreams hang.  For example [id:000132](https://streams.videolan.org/ffmpeg/incoming/id%3A000132%2Csig%3A06%2Csrc%3A005246%2Ctime%3A670094688%2Cexecs%3A293703%2Cop%3Ahavoc%2Crep%3A3) fails on the assertion
https://github.com/ffvvc/FFmpeg/blob/e81b6d78fc2ddf8edd53a6a052713354ef8d27c2/libavcodec/vvc/vvc_thread.c#L182
before the patch, but hangs after the patch.

**Comment by nuomi2021** [comment]
hmm, could you help https://github.com/ffvvc/FFmpeg/issues/218 and add all fixed fuzz clips to failed/fuzz/ ?
thank you

**Comment by nuomi2021** [comment]
@frankplow how about the latest one :)

**Comment by frankplow** [comment]
@nuomi2021 Yes, seems to have done the trick!

**Comment by nuomi2021** [comment]
@frankplow clip name is not valid on Windows :)

**Comment by frankplow** [comment]
> @frankplow clip name is not valid on Windows :)

Fixed in https://github.com/ffvvc/tests/pull/32

**Pull request closed without merging**
